//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemPicker.Tests.Matcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestPosts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestPosts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemPicker.Tests.Matcher.TestPosts", typeof(TestPosts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Day 1&apos;s post](https://www.reddit.com/r/EliteDangerous/comments/l5tqcj/flying_to_sag_a_without_a_fuel_scoop_day_1/)
        ///
        ///I love doing repetitive things. The same actions, the same music, the same sights. It&apos;s a chance to turn autopilot on and focus on thinking about something else. The task still gets done, I just don&apos;t have to pay much attention to it.
        ///
        ///So listening to Josh A&apos;s *Disgrace* was a great chance to turn autopilot on, keep jumping, and think about the feasibility of this trip.
        ///
        ///The only data I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Post1 {
            get {
                return ResourceManager.GetString("Post1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Day 2 Post](https://www.reddit.com/r/EliteDangerous/comments/l67wpu/flying_to_sag_a_without_a_fuel_scoop_day_2/?ref=share&amp;ref_source=link) -- [Ship&apos;s Data Log](https://docs.google.com/spreadsheets/d/1PIXh3RuSctZINwhhbgFtCflcO857qzkKwKlFJvEp580/edit?usp=sharing) -- [Apollo&apos;s Build](https://edsy.org/s/vc6qgwH)
        ///
        ///I&apos;ve got a love-hate relationship with the Anaconda. Mechanically speaking, nothing comes close to it for exploration. It&apos;s got the jump range, the options for outfitting, and the profile of a prope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Post2 {
            get {
                return ResourceManager.GetString("Post2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ah but the supercruise assist module is invaluable to the multitasking commander such as myself! Furthermore, it can be manipulated in such a way to drop out at your destination faster than traditional means since it will drop you out of supercruise even if your speed exceeds the recommended drop out speed! It just so happens that in this case it decided to shove me directly through the station, miraculously without any damage done to myself or the station...
        ///.
        /// </summary>
        internal static string TestComment3 {
            get {
                return ResourceManager.GetString("TestComment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found your Problem Epic New Commader o7.
        ///
        ///Your wasting a 1 slot on a &quot;supercrud assistance program&quot;.
        ///
        ///Might I suggest replacing it with: Anything else
        ///
        ///-Lakon Marketing Division, Keelback Office-&apos;If you Kan&apos;t do it in a KeelBack, you&apos;re just not that good&apos;
        ///.
        /// </summary>
        internal static string TestComment4 {
            get {
                return ResourceManager.GetString("TestComment4", resourceCulture);
            }
        }
    }
}
